const actionTypes = {
  filmActions: {
    GET_FILMS_START: 'GET_FILMS_START',
    GET_FILMS_SUCCESS: 'GET_FILMS_SUCCESS',
    GET_FILMS_FAIL: 'GET_FILMS_FAIL',
    GET_FILTRED_FILMS_SUCCESS: 'GET_FILTRED_FILMS_SUCCESS',
    CLEAR_FILMS:"CLEAR_FILMS",
  },
};

export default actionTypes;
